// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Publication.proto

public final class PublicationOuterClass {
  private PublicationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PublicationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Publication)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string stationid = 1;</code>
     * @return The stationid.
     */
    java.lang.String getStationid();
    /**
     * <code>string stationid = 1;</code>
     * @return The bytes for stationid.
     */
    com.google.protobuf.ByteString
        getStationidBytes();

    /**
     * <code>string city = 2;</code>
     * @return The city.
     */
    java.lang.String getCity();
    /**
     * <code>string city = 2;</code>
     * @return The bytes for city.
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>string temp = 3;</code>
     * @return The temp.
     */
    java.lang.String getTemp();
    /**
     * <code>string temp = 3;</code>
     * @return The bytes for temp.
     */
    com.google.protobuf.ByteString
        getTempBytes();

    /**
     * <code>string wind = 4;</code>
     * @return The wind.
     */
    java.lang.String getWind();
    /**
     * <code>string wind = 4;</code>
     * @return The bytes for wind.
     */
    com.google.protobuf.ByteString
        getWindBytes();
  }
  /**
   * Protobuf type {@code Publication}
   */
  public static final class Publication extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Publication)
      PublicationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Publication.newBuilder() to construct.
    private Publication(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Publication() {
      stationid_ = "";
      city_ = "";
      temp_ = "";
      wind_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Publication();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PublicationOuterClass.internal_static_Publication_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PublicationOuterClass.internal_static_Publication_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PublicationOuterClass.Publication.class, PublicationOuterClass.Publication.Builder.class);
    }

    public static final int STATIONID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object stationid_ = "";
    /**
     * <code>string stationid = 1;</code>
     * @return The stationid.
     */
    @java.lang.Override
    public java.lang.String getStationid() {
      java.lang.Object ref = stationid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stationid_ = s;
        return s;
      }
    }
    /**
     * <code>string stationid = 1;</code>
     * @return The bytes for stationid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStationidBytes() {
      java.lang.Object ref = stationid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stationid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object city_ = "";
    /**
     * <code>string city = 2;</code>
     * @return The city.
     */
    @java.lang.Override
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>string city = 2;</code>
     * @return The bytes for city.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEMP_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object temp_ = "";
    /**
     * <code>string temp = 3;</code>
     * @return The temp.
     */
    @java.lang.Override
    public java.lang.String getTemp() {
      java.lang.Object ref = temp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        temp_ = s;
        return s;
      }
    }
    /**
     * <code>string temp = 3;</code>
     * @return The bytes for temp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTempBytes() {
      java.lang.Object ref = temp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        temp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WIND_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object wind_ = "";
    /**
     * <code>string wind = 4;</code>
     * @return The wind.
     */
    @java.lang.Override
    public java.lang.String getWind() {
      java.lang.Object ref = wind_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wind_ = s;
        return s;
      }
    }
    /**
     * <code>string wind = 4;</code>
     * @return The bytes for wind.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWindBytes() {
      java.lang.Object ref = wind_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wind_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stationid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stationid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, city_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(temp_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, temp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(wind_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, wind_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stationid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stationid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, city_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(temp_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, temp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(wind_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, wind_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PublicationOuterClass.Publication)) {
        return super.equals(obj);
      }
      PublicationOuterClass.Publication other = (PublicationOuterClass.Publication) obj;

      if (!getStationid()
          .equals(other.getStationid())) return false;
      if (!getCity()
          .equals(other.getCity())) return false;
      if (!getTemp()
          .equals(other.getTemp())) return false;
      if (!getWind()
          .equals(other.getWind())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATIONID_FIELD_NUMBER;
      hash = (53 * hash) + getStationid().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (37 * hash) + TEMP_FIELD_NUMBER;
      hash = (53 * hash) + getTemp().hashCode();
      hash = (37 * hash) + WIND_FIELD_NUMBER;
      hash = (53 * hash) + getWind().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PublicationOuterClass.Publication parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PublicationOuterClass.Publication parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PublicationOuterClass.Publication parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PublicationOuterClass.Publication parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PublicationOuterClass.Publication parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PublicationOuterClass.Publication parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PublicationOuterClass.Publication parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PublicationOuterClass.Publication parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static PublicationOuterClass.Publication parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static PublicationOuterClass.Publication parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PublicationOuterClass.Publication parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PublicationOuterClass.Publication parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PublicationOuterClass.Publication prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Publication}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Publication)
        PublicationOuterClass.PublicationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PublicationOuterClass.internal_static_Publication_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PublicationOuterClass.internal_static_Publication_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PublicationOuterClass.Publication.class, PublicationOuterClass.Publication.Builder.class);
      }

      // Construct using PublicationOuterClass.Publication.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        stationid_ = "";
        city_ = "";
        temp_ = "";
        wind_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PublicationOuterClass.internal_static_Publication_descriptor;
      }

      @java.lang.Override
      public PublicationOuterClass.Publication getDefaultInstanceForType() {
        return PublicationOuterClass.Publication.getDefaultInstance();
      }

      @java.lang.Override
      public PublicationOuterClass.Publication build() {
        PublicationOuterClass.Publication result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PublicationOuterClass.Publication buildPartial() {
        PublicationOuterClass.Publication result = new PublicationOuterClass.Publication(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(PublicationOuterClass.Publication result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.stationid_ = stationid_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.city_ = city_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.temp_ = temp_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.wind_ = wind_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PublicationOuterClass.Publication) {
          return mergeFrom((PublicationOuterClass.Publication)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PublicationOuterClass.Publication other) {
        if (other == PublicationOuterClass.Publication.getDefaultInstance()) return this;
        if (!other.getStationid().isEmpty()) {
          stationid_ = other.stationid_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getTemp().isEmpty()) {
          temp_ = other.temp_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getWind().isEmpty()) {
          wind_ = other.wind_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                stationid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                city_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                temp_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                wind_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object stationid_ = "";
      /**
       * <code>string stationid = 1;</code>
       * @return The stationid.
       */
      public java.lang.String getStationid() {
        java.lang.Object ref = stationid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stationid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stationid = 1;</code>
       * @return The bytes for stationid.
       */
      public com.google.protobuf.ByteString
          getStationidBytes() {
        java.lang.Object ref = stationid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stationid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stationid = 1;</code>
       * @param value The stationid to set.
       * @return This builder for chaining.
       */
      public Builder setStationid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        stationid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string stationid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStationid() {
        stationid_ = getDefaultInstance().getStationid();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string stationid = 1;</code>
       * @param value The bytes for stationid to set.
       * @return This builder for chaining.
       */
      public Builder setStationidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        stationid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>string city = 2;</code>
       * @return The city.
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string city = 2;</code>
       * @return The bytes for city.
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string city = 2;</code>
       * @param value The city to set.
       * @return This builder for chaining.
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        city_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string city = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCity() {
        city_ = getDefaultInstance().getCity();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string city = 2;</code>
       * @param value The bytes for city to set.
       * @return This builder for chaining.
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        city_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object temp_ = "";
      /**
       * <code>string temp = 3;</code>
       * @return The temp.
       */
      public java.lang.String getTemp() {
        java.lang.Object ref = temp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          temp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string temp = 3;</code>
       * @return The bytes for temp.
       */
      public com.google.protobuf.ByteString
          getTempBytes() {
        java.lang.Object ref = temp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          temp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string temp = 3;</code>
       * @param value The temp to set.
       * @return This builder for chaining.
       */
      public Builder setTemp(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        temp_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string temp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTemp() {
        temp_ = getDefaultInstance().getTemp();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string temp = 3;</code>
       * @param value The bytes for temp to set.
       * @return This builder for chaining.
       */
      public Builder setTempBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        temp_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object wind_ = "";
      /**
       * <code>string wind = 4;</code>
       * @return The wind.
       */
      public java.lang.String getWind() {
        java.lang.Object ref = wind_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          wind_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string wind = 4;</code>
       * @return The bytes for wind.
       */
      public com.google.protobuf.ByteString
          getWindBytes() {
        java.lang.Object ref = wind_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          wind_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string wind = 4;</code>
       * @param value The wind to set.
       * @return This builder for chaining.
       */
      public Builder setWind(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        wind_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string wind = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearWind() {
        wind_ = getDefaultInstance().getWind();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string wind = 4;</code>
       * @param value The bytes for wind to set.
       * @return This builder for chaining.
       */
      public Builder setWindBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        wind_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Publication)
    }

    // @@protoc_insertion_point(class_scope:Publication)
    private static final PublicationOuterClass.Publication DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PublicationOuterClass.Publication();
    }

    public static PublicationOuterClass.Publication getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Publication>
        PARSER = new com.google.protobuf.AbstractParser<Publication>() {
      @java.lang.Override
      public Publication parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Publication> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Publication> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PublicationOuterClass.Publication getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Publication_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Publication_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Publication.proto\"J\n\013Publication\022\021\n\tst" +
      "ationid\030\001 \001(\t\022\014\n\004city\030\002 \001(\t\022\014\n\004temp\030\003 \001(" +
      "\t\022\014\n\004wind\030\004 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Publication_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Publication_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Publication_descriptor,
        new java.lang.String[] { "Stationid", "City", "Temp", "Wind", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
