// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Subscription.proto

public final class SubscriptionOuterClass {
  private SubscriptionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubscriptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Subscription)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
     */
    java.util.List<SubscriptionOuterClass.Subscription.FieldSubscription> 
        getFieldSubscriptionsList();
    /**
     * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
     */
    SubscriptionOuterClass.Subscription.FieldSubscription getFieldSubscriptions(int index);
    /**
     * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
     */
    int getFieldSubscriptionsCount();
    /**
     * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
     */
    java.util.List<? extends SubscriptionOuterClass.Subscription.FieldSubscriptionOrBuilder> 
        getFieldSubscriptionsOrBuilderList();
    /**
     * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
     */
    SubscriptionOuterClass.Subscription.FieldSubscriptionOrBuilder getFieldSubscriptionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Subscription}
   */
  public static final class Subscription extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Subscription)
      SubscriptionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Subscription.newBuilder() to construct.
    private Subscription(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Subscription() {
      fieldSubscriptions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Subscription();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SubscriptionOuterClass.internal_static_Subscription_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SubscriptionOuterClass.internal_static_Subscription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SubscriptionOuterClass.Subscription.class, SubscriptionOuterClass.Subscription.Builder.class);
    }

    public interface FieldSubscriptionOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Subscription.FieldSubscription)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string key = 1;</code>
       * @return The key.
       */
      java.lang.String getKey();
      /**
       * <code>string key = 1;</code>
       * @return The bytes for key.
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      /**
       * <code>string operator = 2;</code>
       * @return The operator.
       */
      java.lang.String getOperator();
      /**
       * <code>string operator = 2;</code>
       * @return The bytes for operator.
       */
      com.google.protobuf.ByteString
          getOperatorBytes();

      /**
       * <code>string value = 3;</code>
       * @return The value.
       */
      java.lang.String getValue();
      /**
       * <code>string value = 3;</code>
       * @return The bytes for value.
       */
      com.google.protobuf.ByteString
          getValueBytes();
    }
    /**
     * Protobuf type {@code Subscription.FieldSubscription}
     */
    public static final class FieldSubscription extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Subscription.FieldSubscription)
        FieldSubscriptionOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use FieldSubscription.newBuilder() to construct.
      private FieldSubscription(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private FieldSubscription() {
        key_ = "";
        operator_ = "";
        value_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new FieldSubscription();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SubscriptionOuterClass.internal_static_Subscription_FieldSubscription_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SubscriptionOuterClass.internal_static_Subscription_FieldSubscription_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SubscriptionOuterClass.Subscription.FieldSubscription.class, SubscriptionOuterClass.Subscription.FieldSubscription.Builder.class);
      }

      public static final int KEY_FIELD_NUMBER = 1;
      @SuppressWarnings("serial")
      private volatile java.lang.Object key_ = "";
      /**
       * <code>string key = 1;</code>
       * @return The key.
       */
      @java.lang.Override
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @return The bytes for key.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int OPERATOR_FIELD_NUMBER = 2;
      @SuppressWarnings("serial")
      private volatile java.lang.Object operator_ = "";
      /**
       * <code>string operator = 2;</code>
       * @return The operator.
       */
      @java.lang.Override
      public java.lang.String getOperator() {
        java.lang.Object ref = operator_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          operator_ = s;
          return s;
        }
      }
      /**
       * <code>string operator = 2;</code>
       * @return The bytes for operator.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getOperatorBytes() {
        java.lang.Object ref = operator_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          operator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int VALUE_FIELD_NUMBER = 3;
      @SuppressWarnings("serial")
      private volatile java.lang.Object value_ = "";
      /**
       * <code>string value = 3;</code>
       * @return The value.
       */
      @java.lang.Override
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        }
      }
      /**
       * <code>string value = 3;</code>
       * @return The bytes for value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operator_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, operator_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, value_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operator_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, operator_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, value_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof SubscriptionOuterClass.Subscription.FieldSubscription)) {
          return super.equals(obj);
        }
        SubscriptionOuterClass.Subscription.FieldSubscription other = (SubscriptionOuterClass.Subscription.FieldSubscription) obj;

        if (!getKey()
            .equals(other.getKey())) return false;
        if (!getOperator()
            .equals(other.getOperator())) return false;
        if (!getValue()
            .equals(other.getValue())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
        hash = (37 * hash) + OPERATOR_FIELD_NUMBER;
        hash = (53 * hash) + getOperator().hashCode();
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static SubscriptionOuterClass.Subscription.FieldSubscription parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static SubscriptionOuterClass.Subscription.FieldSubscription parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static SubscriptionOuterClass.Subscription.FieldSubscription parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static SubscriptionOuterClass.Subscription.FieldSubscription parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static SubscriptionOuterClass.Subscription.FieldSubscription parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static SubscriptionOuterClass.Subscription.FieldSubscription parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static SubscriptionOuterClass.Subscription.FieldSubscription parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static SubscriptionOuterClass.Subscription.FieldSubscription parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static SubscriptionOuterClass.Subscription.FieldSubscription parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static SubscriptionOuterClass.Subscription.FieldSubscription parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static SubscriptionOuterClass.Subscription.FieldSubscription parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static SubscriptionOuterClass.Subscription.FieldSubscription parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(SubscriptionOuterClass.Subscription.FieldSubscription prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Subscription.FieldSubscription}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Subscription.FieldSubscription)
          SubscriptionOuterClass.Subscription.FieldSubscriptionOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return SubscriptionOuterClass.internal_static_Subscription_FieldSubscription_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return SubscriptionOuterClass.internal_static_Subscription_FieldSubscription_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  SubscriptionOuterClass.Subscription.FieldSubscription.class, SubscriptionOuterClass.Subscription.FieldSubscription.Builder.class);
        }

        // Construct using SubscriptionOuterClass.Subscription.FieldSubscription.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          key_ = "";
          operator_ = "";
          value_ = "";
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return SubscriptionOuterClass.internal_static_Subscription_FieldSubscription_descriptor;
        }

        @java.lang.Override
        public SubscriptionOuterClass.Subscription.FieldSubscription getDefaultInstanceForType() {
          return SubscriptionOuterClass.Subscription.FieldSubscription.getDefaultInstance();
        }

        @java.lang.Override
        public SubscriptionOuterClass.Subscription.FieldSubscription build() {
          SubscriptionOuterClass.Subscription.FieldSubscription result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public SubscriptionOuterClass.Subscription.FieldSubscription buildPartial() {
          SubscriptionOuterClass.Subscription.FieldSubscription result = new SubscriptionOuterClass.Subscription.FieldSubscription(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(SubscriptionOuterClass.Subscription.FieldSubscription result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.key_ = key_;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.operator_ = operator_;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.value_ = value_;
          }
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof SubscriptionOuterClass.Subscription.FieldSubscription) {
            return mergeFrom((SubscriptionOuterClass.Subscription.FieldSubscription)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(SubscriptionOuterClass.Subscription.FieldSubscription other) {
          if (other == SubscriptionOuterClass.Subscription.FieldSubscription.getDefaultInstance()) return this;
          if (!other.getKey().isEmpty()) {
            key_ = other.key_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          if (!other.getOperator().isEmpty()) {
            operator_ = other.operator_;
            bitField0_ |= 0x00000002;
            onChanged();
          }
          if (!other.getValue().isEmpty()) {
            value_ = other.value_;
            bitField0_ |= 0x00000004;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  key_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                case 18: {
                  operator_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 18
                case 26: {
                  value_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000004;
                  break;
                } // case 26
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private java.lang.Object key_ = "";
        /**
         * <code>string key = 1;</code>
         * @return The key.
         */
        public java.lang.String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            key_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string key = 1;</code>
         * @return The bytes for key.
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string key = 1;</code>
         * @param value The key to set.
         * @return This builder for chaining.
         */
        public Builder setKey(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          key_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>string key = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearKey() {
          key_ = getDefaultInstance().getKey();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>string key = 1;</code>
         * @param value The bytes for key to set.
         * @return This builder for chaining.
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          key_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }

        private java.lang.Object operator_ = "";
        /**
         * <code>string operator = 2;</code>
         * @return The operator.
         */
        public java.lang.String getOperator() {
          java.lang.Object ref = operator_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            operator_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string operator = 2;</code>
         * @return The bytes for operator.
         */
        public com.google.protobuf.ByteString
            getOperatorBytes() {
          java.lang.Object ref = operator_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            operator_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string operator = 2;</code>
         * @param value The operator to set.
         * @return This builder for chaining.
         */
        public Builder setOperator(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          operator_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>string operator = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearOperator() {
          operator_ = getDefaultInstance().getOperator();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        /**
         * <code>string operator = 2;</code>
         * @param value The bytes for operator to set.
         * @return This builder for chaining.
         */
        public Builder setOperatorBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          operator_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }

        private java.lang.Object value_ = "";
        /**
         * <code>string value = 3;</code>
         * @return The value.
         */
        public java.lang.String getValue() {
          java.lang.Object ref = value_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            value_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string value = 3;</code>
         * @return The bytes for value.
         */
        public com.google.protobuf.ByteString
            getValueBytes() {
          java.lang.Object ref = value_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            value_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string value = 3;</code>
         * @param value The value to set.
         * @return This builder for chaining.
         */
        public Builder setValue(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          value_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        /**
         * <code>string value = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearValue() {
          value_ = getDefaultInstance().getValue();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
          return this;
        }
        /**
         * <code>string value = 3;</code>
         * @param value The bytes for value to set.
         * @return This builder for chaining.
         */
        public Builder setValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          value_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Subscription.FieldSubscription)
      }

      // @@protoc_insertion_point(class_scope:Subscription.FieldSubscription)
      private static final SubscriptionOuterClass.Subscription.FieldSubscription DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new SubscriptionOuterClass.Subscription.FieldSubscription();
      }

      public static SubscriptionOuterClass.Subscription.FieldSubscription getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<FieldSubscription>
          PARSER = new com.google.protobuf.AbstractParser<FieldSubscription>() {
        @java.lang.Override
        public FieldSubscription parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<FieldSubscription> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<FieldSubscription> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public SubscriptionOuterClass.Subscription.FieldSubscription getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int FIELDSUBSCRIPTIONS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<SubscriptionOuterClass.Subscription.FieldSubscription> fieldSubscriptions_;
    /**
     * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
     */
    @java.lang.Override
    public java.util.List<SubscriptionOuterClass.Subscription.FieldSubscription> getFieldSubscriptionsList() {
      return fieldSubscriptions_;
    }
    /**
     * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends SubscriptionOuterClass.Subscription.FieldSubscriptionOrBuilder> 
        getFieldSubscriptionsOrBuilderList() {
      return fieldSubscriptions_;
    }
    /**
     * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
     */
    @java.lang.Override
    public int getFieldSubscriptionsCount() {
      return fieldSubscriptions_.size();
    }
    /**
     * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
     */
    @java.lang.Override
    public SubscriptionOuterClass.Subscription.FieldSubscription getFieldSubscriptions(int index) {
      return fieldSubscriptions_.get(index);
    }
    /**
     * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
     */
    @java.lang.Override
    public SubscriptionOuterClass.Subscription.FieldSubscriptionOrBuilder getFieldSubscriptionsOrBuilder(
        int index) {
      return fieldSubscriptions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < fieldSubscriptions_.size(); i++) {
        output.writeMessage(1, fieldSubscriptions_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < fieldSubscriptions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, fieldSubscriptions_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SubscriptionOuterClass.Subscription)) {
        return super.equals(obj);
      }
      SubscriptionOuterClass.Subscription other = (SubscriptionOuterClass.Subscription) obj;

      if (!getFieldSubscriptionsList()
          .equals(other.getFieldSubscriptionsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getFieldSubscriptionsCount() > 0) {
        hash = (37 * hash) + FIELDSUBSCRIPTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getFieldSubscriptionsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SubscriptionOuterClass.Subscription parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SubscriptionOuterClass.Subscription parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SubscriptionOuterClass.Subscription parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SubscriptionOuterClass.Subscription parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SubscriptionOuterClass.Subscription parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SubscriptionOuterClass.Subscription parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SubscriptionOuterClass.Subscription parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SubscriptionOuterClass.Subscription parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static SubscriptionOuterClass.Subscription parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static SubscriptionOuterClass.Subscription parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SubscriptionOuterClass.Subscription parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SubscriptionOuterClass.Subscription parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SubscriptionOuterClass.Subscription prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Subscription}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Subscription)
        SubscriptionOuterClass.SubscriptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SubscriptionOuterClass.internal_static_Subscription_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SubscriptionOuterClass.internal_static_Subscription_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SubscriptionOuterClass.Subscription.class, SubscriptionOuterClass.Subscription.Builder.class);
      }

      // Construct using SubscriptionOuterClass.Subscription.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (fieldSubscriptionsBuilder_ == null) {
          fieldSubscriptions_ = java.util.Collections.emptyList();
        } else {
          fieldSubscriptions_ = null;
          fieldSubscriptionsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SubscriptionOuterClass.internal_static_Subscription_descriptor;
      }

      @java.lang.Override
      public SubscriptionOuterClass.Subscription getDefaultInstanceForType() {
        return SubscriptionOuterClass.Subscription.getDefaultInstance();
      }

      @java.lang.Override
      public SubscriptionOuterClass.Subscription build() {
        SubscriptionOuterClass.Subscription result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SubscriptionOuterClass.Subscription buildPartial() {
        SubscriptionOuterClass.Subscription result = new SubscriptionOuterClass.Subscription(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(SubscriptionOuterClass.Subscription result) {
        if (fieldSubscriptionsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            fieldSubscriptions_ = java.util.Collections.unmodifiableList(fieldSubscriptions_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.fieldSubscriptions_ = fieldSubscriptions_;
        } else {
          result.fieldSubscriptions_ = fieldSubscriptionsBuilder_.build();
        }
      }

      private void buildPartial0(SubscriptionOuterClass.Subscription result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SubscriptionOuterClass.Subscription) {
          return mergeFrom((SubscriptionOuterClass.Subscription)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SubscriptionOuterClass.Subscription other) {
        if (other == SubscriptionOuterClass.Subscription.getDefaultInstance()) return this;
        if (fieldSubscriptionsBuilder_ == null) {
          if (!other.fieldSubscriptions_.isEmpty()) {
            if (fieldSubscriptions_.isEmpty()) {
              fieldSubscriptions_ = other.fieldSubscriptions_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFieldSubscriptionsIsMutable();
              fieldSubscriptions_.addAll(other.fieldSubscriptions_);
            }
            onChanged();
          }
        } else {
          if (!other.fieldSubscriptions_.isEmpty()) {
            if (fieldSubscriptionsBuilder_.isEmpty()) {
              fieldSubscriptionsBuilder_.dispose();
              fieldSubscriptionsBuilder_ = null;
              fieldSubscriptions_ = other.fieldSubscriptions_;
              bitField0_ = (bitField0_ & ~0x00000001);
              fieldSubscriptionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFieldSubscriptionsFieldBuilder() : null;
            } else {
              fieldSubscriptionsBuilder_.addAllMessages(other.fieldSubscriptions_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                SubscriptionOuterClass.Subscription.FieldSubscription m =
                    input.readMessage(
                        SubscriptionOuterClass.Subscription.FieldSubscription.parser(),
                        extensionRegistry);
                if (fieldSubscriptionsBuilder_ == null) {
                  ensureFieldSubscriptionsIsMutable();
                  fieldSubscriptions_.add(m);
                } else {
                  fieldSubscriptionsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<SubscriptionOuterClass.Subscription.FieldSubscription> fieldSubscriptions_ =
        java.util.Collections.emptyList();
      private void ensureFieldSubscriptionsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          fieldSubscriptions_ = new java.util.ArrayList<SubscriptionOuterClass.Subscription.FieldSubscription>(fieldSubscriptions_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          SubscriptionOuterClass.Subscription.FieldSubscription, SubscriptionOuterClass.Subscription.FieldSubscription.Builder, SubscriptionOuterClass.Subscription.FieldSubscriptionOrBuilder> fieldSubscriptionsBuilder_;

      /**
       * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
       */
      public java.util.List<SubscriptionOuterClass.Subscription.FieldSubscription> getFieldSubscriptionsList() {
        if (fieldSubscriptionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(fieldSubscriptions_);
        } else {
          return fieldSubscriptionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
       */
      public int getFieldSubscriptionsCount() {
        if (fieldSubscriptionsBuilder_ == null) {
          return fieldSubscriptions_.size();
        } else {
          return fieldSubscriptionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
       */
      public SubscriptionOuterClass.Subscription.FieldSubscription getFieldSubscriptions(int index) {
        if (fieldSubscriptionsBuilder_ == null) {
          return fieldSubscriptions_.get(index);
        } else {
          return fieldSubscriptionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
       */
      public Builder setFieldSubscriptions(
          int index, SubscriptionOuterClass.Subscription.FieldSubscription value) {
        if (fieldSubscriptionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldSubscriptionsIsMutable();
          fieldSubscriptions_.set(index, value);
          onChanged();
        } else {
          fieldSubscriptionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
       */
      public Builder setFieldSubscriptions(
          int index, SubscriptionOuterClass.Subscription.FieldSubscription.Builder builderForValue) {
        if (fieldSubscriptionsBuilder_ == null) {
          ensureFieldSubscriptionsIsMutable();
          fieldSubscriptions_.set(index, builderForValue.build());
          onChanged();
        } else {
          fieldSubscriptionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
       */
      public Builder addFieldSubscriptions(SubscriptionOuterClass.Subscription.FieldSubscription value) {
        if (fieldSubscriptionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldSubscriptionsIsMutable();
          fieldSubscriptions_.add(value);
          onChanged();
        } else {
          fieldSubscriptionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
       */
      public Builder addFieldSubscriptions(
          int index, SubscriptionOuterClass.Subscription.FieldSubscription value) {
        if (fieldSubscriptionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldSubscriptionsIsMutable();
          fieldSubscriptions_.add(index, value);
          onChanged();
        } else {
          fieldSubscriptionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
       */
      public Builder addFieldSubscriptions(
          SubscriptionOuterClass.Subscription.FieldSubscription.Builder builderForValue) {
        if (fieldSubscriptionsBuilder_ == null) {
          ensureFieldSubscriptionsIsMutable();
          fieldSubscriptions_.add(builderForValue.build());
          onChanged();
        } else {
          fieldSubscriptionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
       */
      public Builder addFieldSubscriptions(
          int index, SubscriptionOuterClass.Subscription.FieldSubscription.Builder builderForValue) {
        if (fieldSubscriptionsBuilder_ == null) {
          ensureFieldSubscriptionsIsMutable();
          fieldSubscriptions_.add(index, builderForValue.build());
          onChanged();
        } else {
          fieldSubscriptionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
       */
      public Builder addAllFieldSubscriptions(
          java.lang.Iterable<? extends SubscriptionOuterClass.Subscription.FieldSubscription> values) {
        if (fieldSubscriptionsBuilder_ == null) {
          ensureFieldSubscriptionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, fieldSubscriptions_);
          onChanged();
        } else {
          fieldSubscriptionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
       */
      public Builder clearFieldSubscriptions() {
        if (fieldSubscriptionsBuilder_ == null) {
          fieldSubscriptions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          fieldSubscriptionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
       */
      public Builder removeFieldSubscriptions(int index) {
        if (fieldSubscriptionsBuilder_ == null) {
          ensureFieldSubscriptionsIsMutable();
          fieldSubscriptions_.remove(index);
          onChanged();
        } else {
          fieldSubscriptionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
       */
      public SubscriptionOuterClass.Subscription.FieldSubscription.Builder getFieldSubscriptionsBuilder(
          int index) {
        return getFieldSubscriptionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
       */
      public SubscriptionOuterClass.Subscription.FieldSubscriptionOrBuilder getFieldSubscriptionsOrBuilder(
          int index) {
        if (fieldSubscriptionsBuilder_ == null) {
          return fieldSubscriptions_.get(index);  } else {
          return fieldSubscriptionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
       */
      public java.util.List<? extends SubscriptionOuterClass.Subscription.FieldSubscriptionOrBuilder> 
           getFieldSubscriptionsOrBuilderList() {
        if (fieldSubscriptionsBuilder_ != null) {
          return fieldSubscriptionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(fieldSubscriptions_);
        }
      }
      /**
       * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
       */
      public SubscriptionOuterClass.Subscription.FieldSubscription.Builder addFieldSubscriptionsBuilder() {
        return getFieldSubscriptionsFieldBuilder().addBuilder(
            SubscriptionOuterClass.Subscription.FieldSubscription.getDefaultInstance());
      }
      /**
       * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
       */
      public SubscriptionOuterClass.Subscription.FieldSubscription.Builder addFieldSubscriptionsBuilder(
          int index) {
        return getFieldSubscriptionsFieldBuilder().addBuilder(
            index, SubscriptionOuterClass.Subscription.FieldSubscription.getDefaultInstance());
      }
      /**
       * <code>repeated .Subscription.FieldSubscription fieldSubscriptions = 1;</code>
       */
      public java.util.List<SubscriptionOuterClass.Subscription.FieldSubscription.Builder> 
           getFieldSubscriptionsBuilderList() {
        return getFieldSubscriptionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          SubscriptionOuterClass.Subscription.FieldSubscription, SubscriptionOuterClass.Subscription.FieldSubscription.Builder, SubscriptionOuterClass.Subscription.FieldSubscriptionOrBuilder> 
          getFieldSubscriptionsFieldBuilder() {
        if (fieldSubscriptionsBuilder_ == null) {
          fieldSubscriptionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              SubscriptionOuterClass.Subscription.FieldSubscription, SubscriptionOuterClass.Subscription.FieldSubscription.Builder, SubscriptionOuterClass.Subscription.FieldSubscriptionOrBuilder>(
                  fieldSubscriptions_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          fieldSubscriptions_ = null;
        }
        return fieldSubscriptionsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Subscription)
    }

    // @@protoc_insertion_point(class_scope:Subscription)
    private static final SubscriptionOuterClass.Subscription DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SubscriptionOuterClass.Subscription();
    }

    public static SubscriptionOuterClass.Subscription getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Subscription>
        PARSER = new com.google.protobuf.AbstractParser<Subscription>() {
      @java.lang.Override
      public Subscription parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Subscription> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Subscription> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SubscriptionOuterClass.Subscription getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Subscription_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Subscription_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Subscription_FieldSubscription_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Subscription_FieldSubscription_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Subscription.proto\"\216\001\n\014Subscription\022;\n" +
      "\022fieldSubscriptions\030\001 \003(\0132\037.Subscription" +
      ".FieldSubscription\032A\n\021FieldSubscription\022" +
      "\013\n\003key\030\001 \001(\t\022\020\n\010operator\030\002 \001(\t\022\r\n\005value\030" +
      "\003 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Subscription_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Subscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Subscription_descriptor,
        new java.lang.String[] { "FieldSubscriptions", });
    internal_static_Subscription_FieldSubscription_descriptor =
      internal_static_Subscription_descriptor.getNestedTypes().get(0);
    internal_static_Subscription_FieldSubscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Subscription_FieldSubscription_descriptor,
        new java.lang.String[] { "Key", "Operator", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
